# Main
foreground #c0caf5
background #24283b
selection_foreground #c0caf5
selection_background #2e3c64

# Color Table
color0 #1d202f
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6
color8 #414868
color9 #ff899d
color10 #9fe044
color11 #faba4a
color12 #8db0ff
color13 #c7a9ff
color14 #a4daff
color15 #c0caf5
color16 #ff9e64
color17 #db4b4b

# Cursor & Mouse
cursor #c0caf5
cursor_text_color #24283b
url_color #73daca

# Windows
active_border_color #7aa2f7
inactive_border_color #292e42
bell_border_color #f7768e

# Tabs
active_tab_foreground #a9b1d6
active_tab_background #24283b
inactive_tab_foreground #545c7e
inactive_tab_background #1d202f
tab_bar_background #1d202f
