#!/bin/zsh

print -P "$(cat <<EOF
%B\
%F{2}                        ..'
%F{2}                    ,xNMM.
%F{2}                  .OMMMMo
%F{2}                  lMM"
%F{2}        .;loddo:.  .olloddol;.        %F{2}╦═╗%F{3}─┬─%F{1}┌┐┌%F{5}┌─┐%F{4}┌─┐
%F{2}      cKMMMMMMMMMMNWMMMMMMMMMM0:      %F{2}╠╦╝%F{3} │ %F{1}│││%F{5}│ ┬%F{4}│ │
%F{3}    .KMMMMMMMMMMMMMMMMMMMMMMMWd.      %F{2}╩╚═%F{3}─┴─%F{1}┘└┘%F{5}└─┘%F{4}└─┘
%F{3}    XMMMMMMMMMMMMMMMMMMMMMMMX.
%F{1}   ;MMMMMMMMMMMMMMMMMMMMMMMM:         %fAn opinionated,
%F{1}   :MMMMMMMMMMMMMMMMMMMMMMMM:         %feye-catching, terminal-first,
%F{1}   .MMMMMMMMMMMMMMMMMMMMMMMMX.        %fpseudo-declarative-by-bootstrapping-everything,
%F{1}    kMMMMMMMMMMMMMMMMMMMMMMMMWd.      %fspend-too-much-time-tweaking-to-actually-get-to-work,
%F{5}    'XMMMMMMMMMMMMMMMMMMMMMMMMMMk     %fMacOS configuration.
%F{5}     'XMMMMMMMMMMMMMMMMMMMMMMMMK.
%F{4}       kMMMMMMMMMMMMMMMMMMMMMMd
%F{4}        ;KMMMMMMMWXXWMMMMMMMk.
%F{4}          "cooc*"    "*coo'"%f%b
EOF
)
"

case "$OSTYPE" in
	darwin*) ;;
	*) print -P "%F{red}%BRingo is for MacOS only. Exiting...%b%f" >&2; return 1 ;;
esac
