shell = "zsh"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.completions]
github = "zsh-users/zsh-completions"

[plugins.syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.history-substring-search]
github = "zsh-users/zsh-history-substring-search"
hooks.post = """
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
bindkey -M viins '^[[A' history-substring-search-up
bindkey -M viins '^[[B' history-substring-search-down
"""
